const FRONTEND_URL = process.env.NEXT_PUBLIC_FRONTEND_URL;

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_UR;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export { FRONTEND_URL, SUPABASE_URL, SUPABASE_ANON_KEY };
